
development:
  bucket: pikcam-dev
  access_key_id: xxx
  secret_access_key: xxx
test:
  bucket: pikcam-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: pikcam-pro
  access_key_id: xxx
  secret_access_key: xxx